-- SchoolSafe VPS baseline - 05 exact column defaults from current Cloud baseline

BEGIN;

ALTER TABLE private.account_invitations ALTER COLUMN invited_at SET DEFAULT now();
ALTER TABLE private.account_invitations ALTER COLUMN expires_at SET DEFAULT (now() + '30 days'::interval);
ALTER TABLE private.account_invitations ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE private.notification_push_outbox ALTER COLUMN id SET DEFAULT ('pout_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE private.notification_push_outbox ALTER COLUMN provider SET DEFAULT 'fcm'::text;
ALTER TABLE private.notification_push_outbox ALTER COLUMN payload SET DEFAULT '{}'::jsonb;
ALTER TABLE private.notification_push_outbox ALTER COLUMN status SET DEFAULT 'queued'::text;
ALTER TABLE private.notification_push_outbox ALTER COLUMN attempts SET DEFAULT 0;
ALTER TABLE private.notification_push_outbox ALTER COLUMN next_attempt_at SET DEFAULT now();
ALTER TABLE private.notification_push_outbox ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE private.notification_push_outbox ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE private.parent_phone_access_requests ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE private.parent_phone_access_requests ALTER COLUMN secret SET DEFAULT gen_random_uuid();
ALTER TABLE private.parent_phone_access_requests ALTER COLUMN status SET DEFAULT 'prepared'::text;
ALTER TABLE private.parent_phone_access_requests ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE private.parent_phone_access_requests ALTER COLUMN expires_at SET DEFAULT (now() + '00:30:00'::interval);
ALTER TABLE private.qr_keys ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE private.role_test_runs ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE private.role_test_runs ALTER COLUMN started_at SET DEFAULT now();
ALTER TABLE private.role_test_runs ALTER COLUMN summary SET DEFAULT '{}'::jsonb;
ALTER TABLE private.school_counters ALTER COLUMN counter_value SET DEFAULT 0;
ALTER TABLE private.school_counters ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE private.school_login_rate_limits ALTER COLUMN window_started_at SET DEFAULT now();
ALTER TABLE private.school_login_rate_limits ALTER COLUMN attempts SET DEFAULT 0;
ALTER TABLE private.school_login_rate_limits ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE private.student_exit_notification_outbox ALTER COLUMN id SET DEFAULT ('out_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE private.student_exit_notification_outbox ALTER COLUMN payload SET DEFAULT '{}'::jsonb;
ALTER TABLE private.student_exit_notification_outbox ALTER COLUMN status SET DEFAULT 'queued'::text;
ALTER TABLE private.student_exit_notification_outbox ALTER COLUMN attempts SET DEFAULT 0;
ALTER TABLE private.student_exit_notification_outbox ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.absences ALTER COLUMN status SET DEFAULT 'pending'::text;
ALTER TABLE public.activites_inscriptions ALTER COLUMN active SET DEFAULT true;
ALTER TABLE public.administrative_document_types ALTER COLUMN id SET DEFAULT ('adt_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE public.administrative_document_types ALTER COLUMN is_financial SET DEFAULT false;
ALTER TABLE public.administrative_document_types ALTER COLUMN active SET DEFAULT true;
ALTER TABLE public.administrative_document_types ALTER COLUMN sort_order SET DEFAULT 100;
ALTER TABLE public.administrative_document_types ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.administrative_document_types ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.administrative_documents ALTER COLUMN id SET DEFAULT ('adm_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE public.administrative_documents ALTER COLUMN currency SET DEFAULT 'USD'::text;
ALTER TABLE public.administrative_documents ALTER COLUMN school_year SET DEFAULT private.current_school_year();
ALTER TABLE public.administrative_documents ALTER COLUMN confidentiality SET DEFAULT 'administrative'::text;
ALTER TABLE public.administrative_documents ALTER COLUMN is_financial SET DEFAULT false;
ALTER TABLE public.administrative_documents ALTER COLUMN status SET DEFAULT 'active'::text;
ALTER TABLE public.administrative_documents ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.administrative_documents ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.advances ALTER COLUMN amount SET DEFAULT 0;
ALTER TABLE public.approbations ALTER COLUMN status SET DEFAULT 'pending'::text;
ALTER TABLE public.approbations ALTER COLUMN data SET DEFAULT '{}'::jsonb;
ALTER TABLE public.aps ALTER COLUMN active SET DEFAULT false;
ALTER TABLE public.aps ALTER COLUMN approval_status SET DEFAULT 'pending'::text;
ALTER TABLE public.aps ALTER COLUMN proposed_at SET DEFAULT now();
ALTER TABLE public.aps ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.aps ALTER COLUMN valid_from SET DEFAULT (timezone('Africa/Kinshasa'::text, now()))::date;
ALTER TABLE public.aps ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.attendance ALTER COLUMN manual SET DEFAULT false;
ALTER TABLE public.attendance ALTER COLUMN excused SET DEFAULT false;
ALTER TABLE public.attendance ALTER COLUMN teacher_validated SET DEFAULT false;
ALTER TABLE public.attendance ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.cahier_prep ALTER COLUMN lang SET DEFAULT 'fr'::text;
ALTER TABLE public.cahier_prep ALTER COLUMN status SET DEFAULT 'planifie'::text;
ALTER TABLE public.cahier_prep ALTER COLUMN validated SET DEFAULT false;
ALTER TABLE public.cahier_prep ALTER COLUMN statut SET DEFAULT 'brouillon'::text;
ALTER TABLE public.cahier_texte ALTER COLUMN status SET DEFAULT 'pending'::text;
ALTER TABLE public.cahier_texte ALTER COLUMN lang SET DEFAULT 'fr'::text;
ALTER TABLE public.cantine ALTER COLUMN active SET DEFAULT true;
ALTER TABLE public.cantine_presence ALTER COLUMN present SET DEFAULT true;
ALTER TABLE public.conduct ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.convocations ALTER COLUMN status SET DEFAULT 'pending'::text;
ALTER TABLE public.convocations ALTER COLUMN auto_generated SET DEFAULT false;
ALTER TABLE public.convocations ALTER COLUMN parent_confirmed SET DEFAULT false;
ALTER TABLE public.daily_expenses ALTER COLUMN validated SET DEFAULT false;
ALTER TABLE public.daily_records ALTER COLUMN validated SET DEFAULT false;
ALTER TABLE public.daily_records ALTER COLUMN assigned SET DEFAULT false;
ALTER TABLE public.daily_records ALTER COLUMN annulled SET DEFAULT false;
ALTER TABLE public.daily_reports ALTER COLUMN status SET DEFAULT 'pending'::text;
ALTER TABLE public.daily_reports ALTER COLUMN records SET DEFAULT '[]'::jsonb;
ALTER TABLE public.daily_reports ALTER COLUMN expenses SET DEFAULT '[]'::jsonb;
ALTER TABLE public.daily_reports ALTER COLUMN summary SET DEFAULT '{}'::jsonb;
ALTER TABLE public.devoirs ALTER COLUMN lang SET DEFAULT 'fr'::text;
ALTER TABLE public.devoirs ALTER COLUMN status SET DEFAULT 'published'::text;
ALTER TABLE public.devoirs ALTER COLUMN pdf_local_only SET DEFAULT false;
ALTER TABLE public.devoirs ALTER COLUMN sigs SET DEFAULT '[]'::jsonb;
ALTER TABLE public.direct_primes ALTER COLUMN amount SET DEFAULT 0;
ALTER TABLE public.evaluations ALTER COLUMN criteria SET DEFAULT '{}'::jsonb;
ALTER TABLE public.exetat ALTER COLUMN registered SET DEFAULT false;
ALTER TABLE public.fee_types ALTER COLUMN montant_defaut SET DEFAULT 0;
ALTER TABLE public.fee_types ALTER COLUMN active SET DEFAULT true;
ALTER TABLE public.grades ALTER COLUMN max SET DEFAULT 20;
ALTER TABLE public.grades ALTER COLUMN weight SET DEFAULT 1;
ALTER TABLE public.inscriptions ALTER COLUMN status SET DEFAULT 'pending'::text;
ALTER TABLE public.journal_entries ALTER COLUMN montant SET DEFAULT 0;
ALTER TABLE public.matieres ALTER COLUMN lang SET DEFAULT 'fr'::text;
ALTER TABLE public.matieres ALTER COLUMN active SET DEFAULT true;
ALTER TABLE public.medical ALTER COLUMN vaccines SET DEFAULT '[]'::jsonb;
ALTER TABLE public.medical ALTER COLUMN vax_dates SET DEFAULT '{}'::jsonb;
ALTER TABLE public.messages ALTER COLUMN status SET DEFAULT 'sent'::text;
ALTER TABLE public.messages ALTER COLUMN read SET DEFAULT false;
ALTER TABLE public.notifs ALTER COLUMN type SET DEFAULT 'info'::text;
ALTER TABLE public.notifs ALTER COLUMN read SET DEFAULT false;
ALTER TABLE public.notifs ALTER COLUMN wa_links SET DEFAULT '[]'::jsonb;
ALTER TABLE public.notifs ALTER COLUMN category SET DEFAULT 'information'::text;
ALTER TABLE public.notifs ALTER COLUMN priority SET DEFAULT 'normal'::text;
ALTER TABLE public.notifs ALTER COLUMN privacy_level SET DEFAULT 'normal'::text;
ALTER TABLE public.notifs ALTER COLUMN requires_ack SET DEFAULT false;
ALTER TABLE public.notifs ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.notifs ALTER COLUMN data SET DEFAULT '{}'::jsonb;
ALTER TABLE public.notifs ALTER COLUMN push_requested SET DEFAULT true;
ALTER TABLE public.palmares_publication_history ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.palmares_publication_history ALTER COLUMN archived_at SET DEFAULT now();
ALTER TABLE public.palmares_publications ALTER COLUMN status SET DEFAULT 'draft'::text;
ALTER TABLE public.palmares_publications ALTER COLUMN formula_version SET DEFAULT 'academic_85_conduct_15_v1'::text;
ALTER TABLE public.palmares_publications ALTER COLUMN snapshot SET DEFAULT '[]'::jsonb;
ALTER TABLE public.palmares_publications ALTER COLUMN version SET DEFAULT 1;
ALTER TABLE public.palmares_publications ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.payment_access_exceptions ALTER COLUMN id SET DEFAULT ('pae_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE public.payment_access_exceptions ALTER COLUMN starts_at SET DEFAULT now();
ALTER TABLE public.payment_access_exceptions ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.payment_allocations ALTER COLUMN id SET DEFAULT ('pal_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE public.payment_allocations ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.payment_receipt_counters ALTER COLUMN last_no SET DEFAULT 0;
ALTER TABLE public.payment_receipt_counters ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.payment_scan_log ALTER COLUMN id SET DEFAULT ('psc_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE public.payment_scan_log ALTER COLUMN source SET DEFAULT 'qr'::text;
ALTER TABLE public.payment_scan_log ALTER COLUMN details SET DEFAULT '{}'::jsonb;
ALTER TABLE public.payment_scan_log ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.payment_transactions ALTER COLUMN id SET DEFAULT ('ptx_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE public.payment_transactions ALTER COLUMN currency SET DEFAULT 'USD'::text;
ALTER TABLE public.payment_transactions ALTER COLUMN payment_date SET DEFAULT (timezone('Africa/Kinshasa'::text, now()))::date;
ALTER TABLE public.payment_transactions ALTER COLUMN payment_method SET DEFAULT 'cash'::text;
ALTER TABLE public.payment_transactions ALTER COLUMN status SET DEFAULT 'confirmed'::text;
ALTER TABLE public.payment_transactions ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.payment_transactions ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.payments ALTER COLUMN paid SET DEFAULT false;
ALTER TABLE public.preinscriptions ALTER COLUMN id SET DEFAULT ('pre_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE public.preinscriptions ALTER COLUMN statut SET DEFAULT 'nouvelle'::text;
ALTER TABLE public.preinscriptions ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.preinscriptions ALTER COLUMN expire_le SET DEFAULT ((timezone('Africa/Kinshasa'::text, now()))::date + 30);
ALTER TABLE public.preinscriptions ALTER COLUMN autorisees SET DEFAULT '[]'::jsonb;
ALTER TABLE public.prevision_matiere ALTER COLUMN lang SET DEFAULT 'fr'::text;
ALTER TABLE public.prevision_matiere ALTER COLUMN pourcentage SET DEFAULT 0;
ALTER TABLE public.prevision_matiere ALTER COLUMN validated SET DEFAULT false;
ALTER TABLE public.profiles ALTER COLUMN status SET DEFAULT 'active'::text;
ALTER TABLE public.profiles ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.profiles ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.push_subscriptions ALTER COLUMN id SET DEFAULT ('push_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE public.push_subscriptions ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.push_subscriptions ALTER COLUMN provider SET DEFAULT 'fcm'::text;
ALTER TABLE public.push_subscriptions ALTER COLUMN platform SET DEFAULT 'unknown'::text;
ALTER TABLE public.push_subscriptions ALTER COLUMN active SET DEFAULT true;
ALTER TABLE public.push_subscriptions ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.push_subscriptions ALTER COLUMN last_seen_at SET DEFAULT now();
ALTER TABLE public.push_subscriptions ALTER COLUMN failure_count SET DEFAULT 0;
ALTER TABLE public.rattrapages ALTER COLUMN status SET DEFAULT 'pending'::text;
ALTER TABLE public.rattrapages ALTER COLUMN amount SET DEFAULT 0;
ALTER TABLE public.rattrapages ALTER COLUMN paid SET DEFAULT false;
ALTER TABLE public.rattrapages ALTER COLUMN auto_triggered SET DEFAULT false;
ALTER TABLE public.rattrapages ALTER COLUMN d2_validated SET DEFAULT false;
ALTER TABLE public.rattrapages ALTER COLUMN done SET DEFAULT false;
ALTER TABLE public.rattrapages ALTER COLUMN archived SET DEFAULT false;
ALTER TABLE public.rattrapages ALTER COLUMN payment_signaled SET DEFAULT false;
ALTER TABLE public.rattrapages ALTER COLUMN reminder_sent SET DEFAULT false;
ALTER TABLE public.salaries ALTER COLUMN amount SET DEFAULT 0;
ALTER TABLE public.salaries ALTER COLUMN bonus SET DEFAULT 0;
ALTER TABLE public.salaries ALTER COLUMN rat_prime SET DEFAULT 0;
ALTER TABLE public.salaries ALTER COLUMN deductions SET DEFAULT 0;
ALTER TABLE public.salaries ALTER COLUMN adv_total SET DEFAULT 0;
ALTER TABLE public.salaries ALTER COLUMN net SET DEFAULT 0;
ALTER TABLE public.salaries ALTER COLUMN paid SET DEFAULT false;
ALTER TABLE public.salaries ALTER COLUMN direct_primes_total SET DEFAULT 0;
ALTER TABLE public.sanctions ALTER COLUMN lifted SET DEFAULT false;
ALTER TABLE public.sanctions ALTER COLUMN parent_notified SET DEFAULT false;
ALTER TABLE public.scan_log ALTER COLUMN manual SET DEFAULT false;
ALTER TABLE public.scan_log ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.school_files ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.school_files ALTER COLUMN metadata SET DEFAULT '{}'::jsonb;
ALTER TABLE public.school_files ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.school_files ALTER COLUMN optimized SET DEFAULT false;
ALTER TABLE public.school_profile ALTER COLUMN id SET DEFAULT 1;
ALTER TABLE public.school_profile ALTER COLUMN locale SET DEFAULT 'fr-CD'::text;
ALTER TABLE public.school_profile ALTER COLUMN timezone SET DEFAULT 'Africa/Kinshasa'::text;
ALTER TABLE public.school_profile ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.settings ALTER COLUMN id SET DEFAULT 'main'::text;
ALTER TABLE public.settings ALTER COLUMN currenttrimestre SET DEFAULT 'T1'::text;
ALTER TABLE public.settings ALTER COLUMN feescontrol SET DEFAULT '{"active": false, "trimestre": "T1"}'::jsonb;
ALTER TABLE public.settings ALTER COLUMN fees SET DEFAULT '{"T1": 0, "T2": 0, "T3": 0, "inscription": 0}'::jsonb;
ALTER TABLE public.settings ALTER COLUMN retention SET DEFAULT '{"notifs": 30, "messages": 30, "scan_log": 90, "audit_log": 90, "approbations": 60, "convocations": 90, "messages_unread": 60}'::jsonb;
ALTER TABLE public.settings ALTER COLUMN toggles SET DEFAULT '{}'::jsonb;
ALTER TABLE public.settings ALTER COLUMN trimlocks SET DEFAULT '{"T1": false, "T2": false, "T3": false}'::jsonb;
ALTER TABLE public.settings ALTER COLUMN school SET DEFAULT '{"name": "Le Sage / The Wise School International"}'::jsonb;
ALTER TABLE public.settings ALTER COLUMN year SET DEFAULT '2025-2026'::text;
ALTER TABLE public.settings ALTER COLUMN horaires SET DEFAULT '{}'::jsonb;
ALTER TABLE public.settings ALTER COLUMN session_timeout_min SET DEFAULT 30;
ALTER TABLE public.settings ALTER COLUMN lockdown SET DEFAULT false;
ALTER TABLE public.settings ALTER COLUMN budget_depenses SET DEFAULT 0;
ALTER TABLE public.settings ALTER COLUMN opening_cash SET DEFAULT 0;
ALTER TABLE public.settings ALTER COLUMN opening_bank SET DEFAULT 0;
ALTER TABLE public.settings ALTER COLUMN staff_postes SET DEFAULT '[]'::jsonb;
ALTER TABLE public.settings ALTER COLUMN archived_years SET DEFAULT '[]'::jsonb;
ALTER TABLE public.settings ALTER COLUMN _last_recu_no SET DEFAULT 0;
ALTER TABLE public.site_content ALTER COLUMN id SET DEFAULT 'main'::text;
ALTER TABLE public.site_content ALTER COLUMN school_name SET DEFAULT 'Complexe Scolaire Le Sage'::text;
ALTER TABLE public.site_content ALTER COLUMN school_name_en SET DEFAULT 'The Wise School International'::text;
ALTER TABLE public.site_content ALTER COLUMN programs SET DEFAULT '[]'::jsonb;
ALTER TABLE public.site_content ALTER COLUMN pillars SET DEFAULT '[]'::jsonb;
ALTER TABLE public.site_content ALTER COLUMN stats SET DEFAULT '{}'::jsonb;
ALTER TABLE public.site_content ALTER COLUMN staff SET DEFAULT '[]'::jsonb;
ALTER TABLE public.site_content ALTER COLUMN gallery SET DEFAULT '[]'::jsonb;
ALTER TABLE public.site_content ALTER COLUMN hero_photos SET DEFAULT '[]'::jsonb;
ALTER TABLE public.site_content ALTER COLUMN theme SET DEFAULT 'dark'::text;
ALTER TABLE public.site_content ALTER COLUMN primary_color SET DEFAULT '#c0962e'::text;
ALTER TABLE public.site_content ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.student_exit_events ALTER COLUMN id SET DEFAULT ('exit_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE public.student_exit_events ALTER COLUMN status SET DEFAULT 'prepared'::text;
ALTER TABLE public.student_exit_events ALTER COLUMN quick_flow SET DEFAULT false;
ALTER TABLE public.student_exit_events ALTER COLUMN manual SET DEFAULT false;
ALTER TABLE public.student_exit_events ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.student_exit_events ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.student_fee_obligations ALTER COLUMN id SET DEFAULT ('sfo_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE public.student_fee_obligations ALTER COLUMN installment_no SET DEFAULT 1;
ALTER TABLE public.student_fee_obligations ALTER COLUMN currency SET DEFAULT 'USD'::text;
ALTER TABLE public.student_fee_obligations ALTER COLUMN active SET DEFAULT true;
ALTER TABLE public.student_fee_obligations ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.student_fee_obligations ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.student_primary_parent_history ALTER COLUMN id SET DEFAULT ('pph_'::text || replace((gen_random_uuid())::text, '-'::text, ''::text));
ALTER TABLE public.student_primary_parent_history ALTER COLUMN changed_at SET DEFAULT now();
ALTER TABLE public.students ALTER COLUMN access_blocked SET DEFAULT false;
ALTER TABLE public.students ALTER COLUMN blocked SET DEFAULT false;
ALTER TABLE public.students ALTER COLUMN access_parent SET DEFAULT true;
ALTER TABLE public.students ALTER COLUMN archived SET DEFAULT false;
ALTER TABLE public.students ALTER COLUMN card_printed SET DEFAULT false;
ALTER TABLE public.students ALTER COLUMN card_print_count SET DEFAULT 0;
ALTER TABLE public.students ALTER COLUMN diplome SET DEFAULT false;
ALTER TABLE public.students ALTER COLUMN may_leave_alone SET DEFAULT false;
ALTER TABLE public.teacher_absences ALTER COLUMN status SET DEFAULT 'pending'::text;
ALTER TABLE public.tenafep ALTER COLUMN registered SET DEFAULT false;
ALTER TABLE public.users ALTER COLUMN status SET DEFAULT 'active'::text;
ALTER TABLE public.users ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.users ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.users ALTER COLUMN access_channel SET DEFAULT 'email'::text;
ALTER TABLE public.users ALTER COLUMN must_change_password SET DEFAULT false;
ALTER TABLE public.users ALTER COLUMN login_email_enabled SET DEFAULT true;
ALTER TABLE public.users ALTER COLUMN login_phone_enabled SET DEFAULT true;
ALTER TABLE public.users ALTER COLUMN access_ready SET DEFAULT true;
ALTER TABLE public.versements ALTER COLUMN montant SET DEFAULT 0;
ALTER TABLE public.versements ALTER COLUMN annulled SET DEFAULT false;

COMMIT;
