-- SchoolSafe VPS baseline - 06a primary keys and unique constraints

BEGIN;

ALTER TABLE private.account_invitations ADD CONSTRAINT account_invitations_pkey PRIMARY KEY (email);
ALTER TABLE private.notification_push_outbox ADD CONSTRAINT notification_push_outbox_pkey PRIMARY KEY (id);
ALTER TABLE private.parent_phone_access_requests ADD CONSTRAINT parent_phone_access_requests_pkey PRIMARY KEY (id);
ALTER TABLE private.qr_keys ADD CONSTRAINT qr_keys_pkey PRIMARY KEY (id);
ALTER TABLE private.role_test_runs ADD CONSTRAINT role_test_runs_pkey PRIMARY KEY (id);
ALTER TABLE private.school_counters ADD CONSTRAINT school_counters_pkey PRIMARY KEY (counter_key);
ALTER TABLE private.school_login_rate_limits ADD CONSTRAINT school_login_rate_limits_pkey PRIMARY KEY (key_hash);
ALTER TABLE private.student_exit_notification_outbox ADD CONSTRAINT student_exit_notification_outbox_pkey PRIMARY KEY (id);
ALTER TABLE public.absences ADD CONSTRAINT absences_pkey PRIMARY KEY (id);
ALTER TABLE public.activites ADD CONSTRAINT activites_pkey PRIMARY KEY (id);
ALTER TABLE public.activites_inscriptions ADD CONSTRAINT activites_inscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.administrative_document_types ADD CONSTRAINT administrative_document_types_pkey PRIMARY KEY (id);
ALTER TABLE public.administrative_documents ADD CONSTRAINT administrative_documents_pkey PRIMARY KEY (id);
ALTER TABLE public.advances ADD CONSTRAINT advances_pkey PRIMARY KEY (id);
ALTER TABLE public.appreciations ADD CONSTRAINT appreciations_pkey PRIMARY KEY (id);
ALTER TABLE public.approbations ADD CONSTRAINT approbations_pkey PRIMARY KEY (id);
ALTER TABLE public.aps ADD CONSTRAINT aps_pkey PRIMARY KEY (id);
ALTER TABLE public.attendance ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);
ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.cahier_prep ADD CONSTRAINT cahier_prep_pkey PRIMARY KEY (id);
ALTER TABLE public.cahier_texte ADD CONSTRAINT cahier_texte_pkey PRIMARY KEY (id);
ALTER TABLE public.cantine ADD CONSTRAINT cantine_pkey PRIMARY KEY (id);
ALTER TABLE public.cantine_menus ADD CONSTRAINT cantine_menus_pkey PRIMARY KEY (id);
ALTER TABLE public.cantine_presence ADD CONSTRAINT cantine_presence_pkey PRIMARY KEY (id);
ALTER TABLE public.classes ADD CONSTRAINT classes_pkey PRIMARY KEY (id);
ALTER TABLE public.conduct ADD CONSTRAINT conduct_pkey PRIMARY KEY (id);
ALTER TABLE public.convocations ADD CONSTRAINT convocations_pkey PRIMARY KEY (id);
ALTER TABLE public.daily_expenses ADD CONSTRAINT daily_expenses_pkey PRIMARY KEY (id);
ALTER TABLE public.daily_records ADD CONSTRAINT daily_records_pkey PRIMARY KEY (id);
ALTER TABLE public.daily_reports ADD CONSTRAINT daily_reports_pkey PRIMARY KEY (id);
ALTER TABLE public.devoirs ADD CONSTRAINT devoirs_pkey PRIMARY KEY (id);
ALTER TABLE public.direct_primes ADD CONSTRAINT direct_primes_pkey PRIMARY KEY (id);
ALTER TABLE public.evaluations ADD CONSTRAINT evaluations_pkey PRIMARY KEY (id);
ALTER TABLE public.events ADD CONSTRAINT events_pkey PRIMARY KEY (id);
ALTER TABLE public.exetat ADD CONSTRAINT exetat_pkey PRIMARY KEY (id);
ALTER TABLE public.fee_types ADD CONSTRAINT fee_types_pkey PRIMARY KEY (id);
ALTER TABLE public.grades ADD CONSTRAINT grades_pkey PRIMARY KEY (id);
ALTER TABLE public.inscriptions ADD CONSTRAINT inscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.journal_entries ADD CONSTRAINT journal_entries_pkey PRIMARY KEY (id);
ALTER TABLE public.matieres ADD CONSTRAINT matieres_pkey PRIMARY KEY (id);
ALTER TABLE public.medical ADD CONSTRAINT medical_pkey PRIMARY KEY (id);
ALTER TABLE public.medical_visits ADD CONSTRAINT medical_visits_pkey PRIMARY KEY (id);
ALTER TABLE public.messages ADD CONSTRAINT messages_pkey PRIMARY KEY (id);
ALTER TABLE public.notifs ADD CONSTRAINT notifs_pkey PRIMARY KEY (id);
ALTER TABLE public.palmares_publication_history ADD CONSTRAINT palmares_publication_history_pkey PRIMARY KEY (id);
ALTER TABLE public.palmares_publications ADD CONSTRAINT palmares_publications_pkey PRIMARY KEY (id);
ALTER TABLE public.payment_access_exceptions ADD CONSTRAINT payment_access_exceptions_pkey PRIMARY KEY (id);
ALTER TABLE public.payment_allocations ADD CONSTRAINT payment_allocations_pkey PRIMARY KEY (id);
ALTER TABLE public.payment_receipt_counters ADD CONSTRAINT payment_receipt_counters_pkey PRIMARY KEY (school_year);
ALTER TABLE public.payment_scan_log ADD CONSTRAINT payment_scan_log_pkey PRIMARY KEY (id);
ALTER TABLE public.payment_transactions ADD CONSTRAINT payment_transactions_pkey PRIMARY KEY (id);
ALTER TABLE public.payments ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE public.preinscriptions ADD CONSTRAINT preinscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.prevision_matiere ADD CONSTRAINT prevision_matiere_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.push_subscriptions ADD CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.rattrapages ADD CONSTRAINT rattrapages_pkey PRIMARY KEY (id);
ALTER TABLE public.salaries ADD CONSTRAINT salaries_pkey PRIMARY KEY (id);
ALTER TABLE public.sanctions ADD CONSTRAINT sanctions_pkey PRIMARY KEY (id);
ALTER TABLE public.scan_log ADD CONSTRAINT scan_log_pkey PRIMARY KEY (id);
ALTER TABLE public.school_files ADD CONSTRAINT school_files_pkey PRIMARY KEY (id);
ALTER TABLE public.school_profile ADD CONSTRAINT school_profile_pkey PRIMARY KEY (id);
ALTER TABLE public.settings ADD CONSTRAINT settings_pkey PRIMARY KEY (id);
ALTER TABLE public.site_content ADD CONSTRAINT site_content_pkey PRIMARY KEY (id);
ALTER TABLE public.student_exit_events ADD CONSTRAINT student_exit_events_pkey PRIMARY KEY (id);
ALTER TABLE public.student_fee_obligations ADD CONSTRAINT student_fee_obligations_pkey PRIMARY KEY (id);
ALTER TABLE public.student_primary_parent_history ADD CONSTRAINT student_primary_parent_history_pkey PRIMARY KEY (id);
ALTER TABLE public.students ADD CONSTRAINT students_pkey PRIMARY KEY (id);
ALTER TABLE public.teacher_absences ADD CONSTRAINT teacher_absences_pkey PRIMARY KEY (id);
ALTER TABLE public.teacher_notes ADD CONSTRAINT teacher_notes_pkey PRIMARY KEY (id);
ALTER TABLE public.tenafep ADD CONSTRAINT tenafep_pkey PRIMARY KEY (id);
ALTER TABLE public.timetables ADD CONSTRAINT timetables_pkey PRIMARY KEY (id);
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE public.versements ADD CONSTRAINT versements_pkey PRIMARY KEY (id);

ALTER TABLE private.account_invitations ADD CONSTRAINT account_invitations_auth_user_id_key UNIQUE (auth_user_id);
ALTER TABLE private.notification_push_outbox ADD CONSTRAINT notification_push_outbox_notification_id_device_id_key UNIQUE (notification_id, device_id);
ALTER TABLE private.student_exit_notification_outbox ADD CONSTRAINT exit_outbox_unique UNIQUE (exit_event_id, notification_type, channel);
ALTER TABLE public.administrative_document_types ADD CONSTRAINT administrative_document_types_code_key UNIQUE (code);
ALTER TABLE public.palmares_publications ADD CONSTRAINT palmares_publications_cid_year_trimestre_key UNIQUE (cid, year, trimestre);
ALTER TABLE public.payment_allocations ADD CONSTRAINT payment_allocations_transaction_id_obligation_id_key UNIQUE (transaction_id, obligation_id);
ALTER TABLE public.payment_transactions ADD CONSTRAINT payment_transactions_receipt_no_key UNIQUE (receipt_no);
ALTER TABLE public.school_files ADD CONSTRAINT school_files_storage_path_key UNIQUE (storage_path);
ALTER TABLE public.student_fee_obligations ADD CONSTRAINT student_fee_obligations_sid_fee_type_id_school_year_install_key UNIQUE (sid, fee_type_id, school_year, installment_no);
ALTER TABLE public.users ADD CONSTRAINT users_auth_user_id_key UNIQUE (auth_user_id);
ALTER TABLE public.users ADD CONSTRAINT users_email_key UNIQUE (email);

COMMIT;
