-- SchoolSafe VPS baseline - 06b CHECK constraints

BEGIN;

ALTER TABLE private.account_invitations ADD CONSTRAINT account_invitations_check CHECK (expires_at > invited_at);
ALTER TABLE private.account_invitations ADD CONSTRAINT account_invitations_email_check CHECK (email = lower(email));
ALTER TABLE private.account_invitations ADD CONSTRAINT account_invitations_role_check CHECK (role = ANY (ARRAY['direction'::text, 'direction2'::text, 'direction3'::text, 'direction_pedagogique'::text, 'caisse'::text, 'enseignant'::text, 'gardien'::text, 'parent'::text]));
ALTER TABLE private.notification_push_outbox ADD CONSTRAINT notification_push_outbox_attempts_check CHECK (attempts >= 0 AND attempts <= 100);
ALTER TABLE private.notification_push_outbox ADD CONSTRAINT notification_push_outbox_provider_check CHECK (provider = ANY (ARRAY['fcm'::text, 'webpush'::text]));
ALTER TABLE private.notification_push_outbox ADD CONSTRAINT notification_push_outbox_status_check CHECK (status = ANY (ARRAY['queued'::text, 'sending'::text, 'sent'::text, 'failed'::text, 'dead'::text]));
ALTER TABLE private.parent_phone_access_requests ADD CONSTRAINT parent_phone_access_requests_action_check CHECK (action = ANY (ARRAY['provision'::text, 'reset'::text, 'change_phone'::text]));
ALTER TABLE private.parent_phone_access_requests ADD CONSTRAINT parent_phone_access_requests_status_check CHECK (status = ANY (ARRAY['prepared'::text, 'auth_linked'::text, 'ready'::text, 'completed'::text, 'failed'::text, 'expired'::text]));
ALTER TABLE private.school_counters ADD CONSTRAINT school_counters_counter_value_check CHECK (counter_value >= 0);
ALTER TABLE private.school_login_rate_limits ADD CONSTRAINT school_login_rate_limits_attempts_check CHECK (attempts >= 0);
ALTER TABLE private.school_login_rate_limits ADD CONSTRAINT school_login_rate_limits_key_hash_check CHECK (key_hash ~ '^[0-9a-f]{64}$'::text);
ALTER TABLE private.student_exit_notification_outbox ADD CONSTRAINT exit_outbox_channel_check CHECK (channel = ANY (ARRAY['app'::text, 'email'::text, 'whatsapp'::text]));
ALTER TABLE private.student_exit_notification_outbox ADD CONSTRAINT exit_outbox_status_check CHECK (status = ANY (ARRAY['queued'::text, 'sent'::text, 'failed'::text, 'skipped'::text]));
ALTER TABLE private.student_exit_notification_outbox ADD CONSTRAINT exit_outbox_type_check CHECK (notification_type = ANY (ARRAY['exit_prepared'::text, 'exit_confirmed'::text, 'exit_refused'::text, 'exit_cancelled'::text, 'exit_expired'::text]));
ALTER TABLE public.administrative_document_types ADD CONSTRAINT administrative_document_types_code_check CHECK (code ~ '^[a-z0-9_]{2,60}$'::text);
ALTER TABLE public.administrative_document_types ADD CONSTRAINT administrative_document_types_group_code_check CHECK (group_code = ANY (ARRAY['utilities'::text, 'insurance'::text, 'rent'::text, 'tax_social'::text, 'supplier'::text, 'banking'::text, 'legal'::text, 'human_resources'::text, 'maintenance'::text, 'inventory'::text, 'correspondence'::text, 'other'::text]));
ALTER TABLE public.administrative_document_types ADD CONSTRAINT administrative_document_types_label_check CHECK (char_length(TRIM(BOTH FROM label)) >= 2 AND char_length(TRIM(BOTH FROM label)) <= 120);
ALTER TABLE public.administrative_document_types ADD CONSTRAINT administrative_document_types_sort_order_check CHECK (sort_order >= 0 AND sort_order <= 10000);
ALTER TABLE public.administrative_documents ADD CONSTRAINT administrative_documents_amount_check CHECK (amount IS NULL OR amount >= 0::numeric);
ALTER TABLE public.administrative_documents ADD CONSTRAINT administrative_documents_confidentiality_check CHECK (confidentiality = ANY (ARRAY['administrative'::text, 'financial'::text, 'restricted'::text]));
ALTER TABLE public.administrative_documents ADD CONSTRAINT administrative_documents_currency_check CHECK (currency = ANY (ARRAY['USD'::text, 'CDF'::text]));
ALTER TABLE public.administrative_documents ADD CONSTRAINT administrative_documents_period_check CHECK (period_start IS NULL OR period_end IS NULL OR period_end >= period_start);
ALTER TABLE public.administrative_documents ADD CONSTRAINT administrative_documents_school_year_check CHECK (school_year ~ '^\d{4}-\d{4}$'::text);
ALTER TABLE public.administrative_documents ADD CONSTRAINT administrative_documents_status_check CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text, 'voided'::text]));
ALTER TABLE public.administrative_documents ADD CONSTRAINT administrative_documents_title_check CHECK (char_length(TRIM(BOTH FROM title)) >= 2 AND char_length(TRIM(BOTH FROM title)) <= 180);
ALTER TABLE public.aps ADD CONSTRAINT aps_active_requires_approval_check CHECK (NOT active OR approval_status = 'approved'::text AND length(btrim(COALESCE(photo, ''::text))) > 0 AND length(btrim(COALESCE(photo_full_body, ''::text))) > 0 AND length(btrim(COALESCE(id_doc_type, ''::text))) > 0 AND length(btrim(COALESCE(id_doc_last4, ''::text))) >= 2 AND length(btrim(COALESCE(id_doc_last4, ''::text))) <= 12);
ALTER TABLE public.aps ADD CONSTRAINT aps_approval_status_check CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'suspended'::text]));
ALTER TABLE public.aps ADD CONSTRAINT aps_photo_reference_check CHECK ((photo IS NULL OR lower(photo) !~~ 'data:%'::text) AND (photo_full_body IS NULL OR lower(photo_full_body) !~~ 'data:%'::text));
ALTER TABLE public.aps ADD CONSTRAINT aps_required_identity_check CHECK (length(btrim(name)) >= 3 AND length(btrim(name)) <= 200 AND length(btrim(relation)) >= 2 AND length(btrim(relation)) <= 100 AND phone ~ '^\+[1-9][0-9]{7,14}$'::text AND (valid_until IS NULL OR valid_until >= valid_from));
ALTER TABLE public.conduct ADD CONSTRAINT conduct_trimestre_check CHECK (trimestre = ANY (ARRAY['T1'::text, 'T2'::text, 'T3'::text]));
ALTER TABLE public.conduct ADD CONSTRAINT conduct_year_format_check CHECK (year ~ '^\d{4}-\d{4}$'::text);
ALTER TABLE public.notifs ADD CONSTRAINT notifs_category_check CHECK (category = ANY (ARRAY['information'::text, 'emergency'::text, 'convocation'::text, 'exit_prepared'::text, 'exit_confirmed'::text, 'exit_cancelled'::text, 'exit_refused'::text, 'exit_expired'::text, 'absence'::text, 'lateness'::text, 'homework'::text, 'assessment'::text, 'result_available'::text, 'teacher_message'::text, 'direction_message'::text, 'announcement'::text, 'administrative_reminder'::text, 'payment'::text, 'receipt_available'::text, 'schedule_change'::text, 'document_available'::text, 'security'::text]));
ALTER TABLE public.notifs ADD CONSTRAINT notifs_priority_check CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text]));
ALTER TABLE public.notifs ADD CONSTRAINT notifs_privacy_level_check CHECK (privacy_level = ANY (ARRAY['normal'::text, 'sensitive'::text]));
ALTER TABLE public.notifs ADD CONSTRAINT notifs_text_limits_check CHECK (length(COALESCE(title, ''::text)) <= 200 AND length(COALESCE(msg, ''::text)) <= 4000 AND length(COALESCE(action_url, ''::text)) <= 1000 AND length(COALESCE(source_type, ''::text)) <= 100 AND length(COALESCE(source_id, ''::text)) <= 200 AND length(COALESCE(dedupe_key, ''::text)) <= 300);
ALTER TABLE public.palmares_publications ADD CONSTRAINT palmares_publications_status_check CHECK (status = ANY (ARRAY['draft'::text, 'reviewed'::text, 'published'::text, 'withdrawn'::text]));
ALTER TABLE public.palmares_publications ADD CONSTRAINT palmares_publications_version_check CHECK (version > 0);
ALTER TABLE public.payment_access_exceptions ADD CONSTRAINT payment_access_exceptions_check CHECK (ends_at > starts_at);
ALTER TABLE public.payment_access_exceptions ADD CONSTRAINT payment_access_exceptions_reason_check CHECK (length(btrim(reason)) >= 3);
ALTER TABLE public.payment_allocations ADD CONSTRAINT payment_allocations_amount_check CHECK (amount > 0::numeric);
ALTER TABLE public.payment_receipt_counters ADD CONSTRAINT payment_receipt_counters_last_no_check CHECK (last_no >= 0);
ALTER TABLE public.payment_scan_log ADD CONSTRAINT payment_scan_log_result_code_check CHECK (result_code = ANY (ARRAY['allowed'::text, 'orient'::text, 'blocked'::text, 'exception'::text, 'unavailable'::text]));
ALTER TABLE public.payment_scan_log ADD CONSTRAINT payment_scan_log_source_check CHECK (source = ANY (ARRAY['qr'::text, 'manual'::text]));
ALTER TABLE public.payment_transactions ADD CONSTRAINT payment_transactions_amount_check CHECK (amount > 0::numeric);
ALTER TABLE public.payment_transactions ADD CONSTRAINT payment_transactions_currency_check CHECK (currency ~ '^[A-Z]{3}$'::text);
ALTER TABLE public.payment_transactions ADD CONSTRAINT payment_transactions_payment_method_check CHECK (payment_method = ANY (ARRAY['cash'::text, 'bank'::text, 'mobile_money'::text, 'other'::text]));
ALTER TABLE public.payment_transactions ADD CONSTRAINT payment_transactions_status_check CHECK (status = ANY (ARRAY['confirmed'::text, 'reversed'::text, 'voided'::text]));
ALTER TABLE public.preinscriptions ADD CONSTRAINT preinscriptions_autorisees_check CHECK (jsonb_typeof(autorisees) = 'array'::text AND jsonb_array_length(autorisees) <= 3);
ALTER TABLE public.preinscriptions ADD CONSTRAINT preinscriptions_classe_check CHECK (length(btrim(classe)) >= 1 AND length(btrim(classe)) <= 160);
ALTER TABLE public.preinscriptions ADD CONSTRAINT preinscriptions_contact_required_check CHECK (private.normalize_phone_e164(telephone) IS NOT NULL AND (email IS NULL OR email = lower(btrim(email)) AND length(email) <= 320 AND email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'::text));
ALTER TABLE public.preinscriptions ADD CONSTRAINT preinscriptions_email_check CHECK (email IS NULL OR length(email) <= 320 AND email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'::text);
ALTER TABLE public.preinscriptions ADD CONSTRAINT preinscriptions_nom_check CHECK (length(btrim(nom)) >= 2 AND length(btrim(nom)) <= 200);
ALTER TABLE public.preinscriptions ADD CONSTRAINT preinscriptions_refusal_check CHECK (statut <> 'refusee'::text OR length(btrim(COALESCE(motif_refus, ''::text))) >= 3);
ALTER TABLE public.preinscriptions ADD CONSTRAINT preinscriptions_sexe_check CHECK (length(btrim(sexe)) >= 1 AND length(btrim(sexe)) <= 30);
ALTER TABLE public.preinscriptions ADD CONSTRAINT preinscriptions_statut_check CHECK (statut = ANY (ARRAY['nouvelle'::text, 'validee'::text, 'refusee'::text]));
ALTER TABLE public.preinscriptions ADD CONSTRAINT preinscriptions_telephone_check CHECK (length(regexp_replace(telephone, '[^0-9]+'::text, ''::text, 'g'::text)) >= 8);
ALTER TABLE public.preinscriptions ADD CONSTRAINT preinscriptions_tutelle_check CHECK (length(btrim(tutelle)) >= 3 AND length(btrim(tutelle)) <= 300);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_phone_e164_check CHECK (phone IS NULL OR phone ~ '^\+[1-9][0-9]{7,14}$'::text);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK (role = ANY (ARRAY['direction'::text, 'direction_pedagogique'::text, 'caisse'::text, 'enseignant'::text, 'gardien'::text, 'parent'::text, 'direction2'::text, 'direction3'::text]));
ALTER TABLE public.profiles ADD CONSTRAINT profiles_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text]));
ALTER TABLE public.push_subscriptions ADD CONSTRAINT push_subscriptions_address_check CHECK (provider = 'fcm'::text AND token IS NOT NULL AND length(token) >= 20 AND length(token) <= 4096 OR provider = 'webpush'::text AND endpoint IS NOT NULL AND auth IS NOT NULL AND p256dh IS NOT NULL);
ALTER TABLE public.push_subscriptions ADD CONSTRAINT push_subscriptions_platform_check CHECK (platform = ANY (ARRAY['web'::text, 'android'::text, 'ios'::text, 'unknown'::text]));
ALTER TABLE public.push_subscriptions ADD CONSTRAINT push_subscriptions_provider_check CHECK (provider = ANY (ARRAY['fcm'::text, 'webpush'::text]));
ALTER TABLE public.school_files ADD CONSTRAINT school_files_academic_year_format_check CHECK (academic_year ~ '^\d{4}-\d{4}$'::text);
ALTER TABLE public.school_files ADD CONSTRAINT school_files_category_check CHECK (category = ANY (ARRAY['document'::text, 'photo'::text, 'identity'::text, 'card'::text, 'receipt'::text, 'homework'::text, 'report'::text, 'archive'::text, 'teacher_preparation'::text, 'administrative_document'::text]));
ALTER TABLE public.school_files ADD CONSTRAINT school_files_compression_profile_check CHECK (compression_profile IS NULL OR (compression_profile = ANY (ARRAY['photo'::text, 'identity'::text, 'card'::text, 'document'::text, 'passthrough'::text])));
ALTER TABLE public.school_files ADD CONSTRAINT school_files_compression_quality_check CHECK (compression_quality IS NULL OR compression_quality >= 1 AND compression_quality <= 100);
ALTER TABLE public.school_files ADD CONSTRAINT school_files_mime_type_check CHECK (mime_type = ANY (ARRAY['image/jpeg'::text, 'image/png'::text, 'image/webp'::text, 'application/pdf'::text]));
ALTER TABLE public.school_files ADD CONSTRAINT school_files_optimization_consistency_check CHECK (NOT optimized OR (source_mime_type = ANY (ARRAY['image/jpeg'::text, 'image/png'::text, 'image/webp'::text])) AND source_size_bytes IS NOT NULL AND source_width IS NOT NULL AND source_height IS NOT NULL AND processed_width IS NOT NULL AND processed_height IS NOT NULL AND compression_quality IS NOT NULL AND compression_profile IS NOT NULL AND optimization_version IS NOT NULL);
ALTER TABLE public.school_files ADD CONSTRAINT school_files_optimization_version_check CHECK (optimization_version IS NULL OR optimization_version >= 1 AND optimization_version <= 100);
ALTER TABLE public.school_files ADD CONSTRAINT school_files_owner_link_check CHECK (owner_type = 'cahier_prep'::text AND cahier_prep_id IS NOT NULL AND owner_id = cahier_prep_id AND administrative_document_id IS NULL OR owner_type = 'administrative_document'::text AND administrative_document_id IS NOT NULL AND owner_id = administrative_document_id AND cahier_prep_id IS NULL OR (owner_type <> ALL (ARRAY['cahier_prep'::text, 'administrative_document'::text])) AND cahier_prep_id IS NULL AND administrative_document_id IS NULL);
ALTER TABLE public.school_files ADD CONSTRAINT school_files_owner_type_check CHECK (owner_type = ANY (ARRAY['student'::text, 'user'::text, 'authorized_person'::text, 'class'::text, 'school'::text, 'devoir'::text, 'cahier_prep'::text, 'administrative_document'::text]));
ALTER TABLE public.school_files ADD CONSTRAINT school_files_processed_dimensions_check CHECK (processed_width IS NULL AND processed_height IS NULL OR processed_width >= 1 AND processed_width <= 12000 AND processed_height >= 1 AND processed_height <= 12000);
ALTER TABLE public.school_files ADD CONSTRAINT school_files_size_bytes_check CHECK (size_bytes > 0 AND size_bytes <= 5242880);
ALTER TABLE public.school_files ADD CONSTRAINT school_files_source_dimensions_check CHECK (source_width IS NULL AND source_height IS NULL OR source_width >= 1 AND source_width <= 12000 AND source_height >= 1 AND source_height <= 12000 AND (source_width::bigint * source_height::bigint) <= 40000000);
ALTER TABLE public.school_files ADD CONSTRAINT school_files_source_mime_type_check CHECK (source_mime_type IS NULL OR (source_mime_type = ANY (ARRAY['image/jpeg'::text, 'image/png'::text, 'image/webp'::text, 'application/pdf'::text])));
ALTER TABLE public.school_files ADD CONSTRAINT school_files_source_size_check CHECK (source_size_bytes IS NULL OR source_size_bytes > 0 AND source_size_bytes <= 8388608);
ALTER TABLE public.school_profile ADD CONSTRAINT school_profile_id_check CHECK (id = 1);
ALTER TABLE public.site_content ADD CONSTRAINT site_content_gallery_check CHECK (jsonb_typeof(gallery) = 'array'::text);
ALTER TABLE public.site_content ADD CONSTRAINT site_content_hero_photos_check CHECK (jsonb_typeof(hero_photos) = 'array'::text);
ALTER TABLE public.site_content ADD CONSTRAINT site_content_id_check CHECK (id = 'main'::text);
ALTER TABLE public.site_content ADD CONSTRAINT site_content_pillars_check CHECK (jsonb_typeof(pillars) = 'array'::text);
ALTER TABLE public.site_content ADD CONSTRAINT site_content_primary_color_check CHECK (primary_color ~ '^#[0-9A-Fa-f]{6}$'::text);
ALTER TABLE public.site_content ADD CONSTRAINT site_content_programs_check CHECK (jsonb_typeof(programs) = 'array'::text);
ALTER TABLE public.site_content ADD CONSTRAINT site_content_staff_check CHECK (jsonb_typeof(staff) = 'array'::text);
ALTER TABLE public.site_content ADD CONSTRAINT site_content_stats_check CHECK (jsonb_typeof(stats) = 'object'::text);
ALTER TABLE public.site_content ADD CONSTRAINT site_content_theme_check CHECK (theme = ANY (ARRAY['dark'::text, 'light'::text, 'custom'::text]));
ALTER TABLE public.student_exit_events ADD CONSTRAINT student_exit_escort_kind_check CHECK (escort_kind IS NULL OR (escort_kind = ANY (ARRAY['primary'::text, 'accredited'::text, 'self'::text])));
ALTER TABLE public.student_exit_events ADD CONSTRAINT student_exit_expiry_check CHECK (expires_at > prepared_at);
ALTER TABLE public.student_exit_events ADD CONSTRAINT student_exit_prepared_role_check CHECK (prepared_by_role = ANY (ARRAY['direction'::text, 'direction2'::text, 'enseignant'::text, 'gardien'::text]));
ALTER TABLE public.student_exit_events ADD CONSTRAINT student_exit_scanner_role_check CHECK (gate_scanned_by_role IS NULL OR (gate_scanned_by_role = ANY (ARRAY['direction'::text, 'direction2'::text, 'enseignant'::text, 'gardien'::text])));
ALTER TABLE public.student_exit_events ADD CONSTRAINT student_exit_status_check CHECK (status = ANY (ARRAY['prepared'::text, 'gate_scanned'::text, 'confirmed'::text, 'refused'::text, 'cancelled'::text, 'expired'::text]));
ALTER TABLE public.student_exit_events ADD CONSTRAINT student_exit_validator_role_check CHECK (validated_by_role IS NULL OR (validated_by_role = ANY (ARRAY['direction'::text, 'direction2'::text, 'enseignant'::text, 'gardien'::text])));
ALTER TABLE public.student_fee_obligations ADD CONSTRAINT student_fee_obligations_amount_due_check CHECK (amount_due >= 0::numeric);
ALTER TABLE public.student_fee_obligations ADD CONSTRAINT student_fee_obligations_currency_check CHECK (currency ~ '^[A-Z]{3}$'::text);
ALTER TABLE public.student_fee_obligations ADD CONSTRAINT student_fee_obligations_installment_no_check CHECK (installment_no > 0);
ALTER TABLE public.users ADD CONSTRAINT users_access_channel_check CHECK (access_channel = ANY (ARRAY['email'::text, 'phone_whatsapp'::text]));
ALTER TABLE public.users ADD CONSTRAINT users_email_normalized_check CHECK (email IS NULL OR email = lower(btrim(email)) AND length(email) <= 320 AND email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'::text);
ALTER TABLE public.users ADD CONSTRAINT users_identity_photo_reference_check CHECK (identity_full_body_photo_url IS NULL OR lower(identity_full_body_photo_url) !~~ 'data:%'::text);
ALTER TABLE public.users ADD CONSTRAINT users_phone_e164_check CHECK (phone IS NULL OR phone ~ '^\+[1-9][0-9]{7,14}$'::text);
ALTER TABLE public.users ADD CONSTRAINT users_primary_contact_available_check CHECK (access_channel = 'email'::text AND email IS NOT NULL OR access_channel = 'phone_whatsapp'::text AND phone IS NOT NULL);
ALTER TABLE public.users ADD CONSTRAINT users_role_check CHECK (role = ANY (ARRAY['direction'::text, 'direction_pedagogique'::text, 'caisse'::text, 'enseignant'::text, 'gardien'::text, 'parent'::text, 'direction2'::text, 'direction3'::text]));
ALTER TABLE public.users ADD CONSTRAINT users_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text]));

COMMIT;
