-- SchoolSafe VPS baseline - 07 non-constraint indexes
-- PK/UNIQUE backing indexes from 06a are intentionally excluded.

BEGIN;

CREATE UNIQUE INDEX account_invitations_id_key ON private.account_invitations USING btree (id);
CREATE INDEX account_invitations_invited_by_idx ON private.account_invitations USING btree (invited_by) WHERE (invited_by IS NOT NULL);
CREATE UNIQUE INDEX account_invitations_pending_app_user_key ON private.account_invitations USING btree (app_user_id) WHERE ((accepted_at IS NULL) AND (app_user_id IS NOT NULL));
CREATE INDEX idx_notification_push_outbox_claim ON private.notification_push_outbox USING btree (status, next_attempt_at, created_at) WHERE (status = ANY (ARRAY['queued'::text, 'failed'::text, 'sending'::text]));
CREATE INDEX idx_notification_push_outbox_notification ON private.notification_push_outbox USING btree (notification_id, status);
CREATE UNIQUE INDEX parent_phone_access_one_active_idx ON private.parent_phone_access_requests USING btree (app_user_id) WHERE (status = ANY (ARRAY['prepared'::text, 'auth_linked'::text, 'ready'::text]));
CREATE INDEX parent_phone_access_requested_by_idx ON private.parent_phone_access_requests USING btree (requested_by);
CREATE INDEX parent_phone_access_target_created_idx ON private.parent_phone_access_requests USING btree (app_user_id, created_at DESC);

CREATE INDEX administrative_documents_idx_archive_lookup ON public.administrative_documents USING btree (school_year, archived_at DESC) WHERE (status = 'archived'::text);
CREATE INDEX administrative_documents_idx_archived_by ON public.administrative_documents USING btree (archived_by) WHERE (archived_by IS NOT NULL);
CREATE INDEX administrative_documents_idx_created_by ON public.administrative_documents USING btree (created_by) WHERE (created_by IS NOT NULL);
CREATE INDEX administrative_documents_idx_financial ON public.administrative_documents USING btree (is_financial, created_at DESC);
CREATE INDEX administrative_documents_idx_provider ON public.administrative_documents USING btree (lower(provider)) WHERE (provider IS NOT NULL);
CREATE INDEX administrative_documents_idx_restored_by ON public.administrative_documents USING btree (restored_by) WHERE (restored_by IS NOT NULL);
CREATE INDEX administrative_documents_idx_type_date ON public.administrative_documents USING btree (document_type_id, document_date DESC, created_at DESC);
CREATE INDEX administrative_documents_idx_year_status ON public.administrative_documents USING btree (school_year, status, created_at DESC);
CREATE INDEX advances_user_id_idx ON public.advances USING btree (user_id);
CREATE INDEX idx_appreciations_sid ON public.appreciations USING btree (sid);
CREATE INDEX idx_approbations_status ON public.approbations USING btree (status);
CREATE UNIQUE INDEX aps_unique_active_identity ON public.aps USING btree (sid, lower(name), phone) WHERE ((approval_status = ANY (ARRAY['pending'::text, 'approved'::text])) AND (active IS NOT FALSE));
CREATE INDEX idx_aps_sid ON public.aps USING btree (sid);
CREATE UNIQUE INDEX attendance_one_record_per_student_day ON public.attendance USING btree (sid, date) WHERE ((sid IS NOT NULL) AND (date IS NOT NULL));
CREATE INDEX idx_attendance_sid_date ON public.attendance USING btree (sid, date);
CREATE INDEX idx_audit_log_date ON public.audit_log USING btree (date);
CREATE INDEX idx_cahier_prep_cid ON public.cahier_prep USING btree (cid);
CREATE INDEX idx_cantine_presence_date ON public.cantine_presence USING btree (date);
CREATE INDEX idx_conduct_sid ON public.conduct USING btree (sid);
CREATE INDEX idx_conduct_sid_year_trimestre_date ON public.conduct USING btree (sid, year, trimestre, date);
CREATE INDEX idx_convocations_sid ON public.convocations USING btree (sid);
CREATE INDEX idx_daily_expenses_date ON public.daily_expenses USING btree (date);
CREATE INDEX idx_daily_records_date ON public.daily_records USING btree (date);
CREATE INDEX idx_devoirs_cid ON public.devoirs USING btree (cid);
CREATE INDEX idx_direct_primes_teacher ON public.direct_primes USING btree (teacher_id);
CREATE INDEX idx_exetat_sid ON public.exetat USING btree (sid);
CREATE INDEX idx_grades_cid ON public.grades USING btree (cid);
CREATE INDEX idx_grades_sid_trim ON public.grades USING btree (sid, trimestre);
CREATE INDEX idx_journal_entries_date ON public.journal_entries USING btree (date);
CREATE INDEX idx_medical_visits_sid ON public.medical_visits USING btree (sid);
CREATE INDEX idx_messages_from_date ON public.messages USING btree ("from", date);
CREATE INDEX idx_messages_to_date ON public.messages USING btree ("to", date);
CREATE INDEX idx_notifs_recipient_created ON public.notifs USING btree (uid, created_at DESC);
CREATE INDEX idx_notifs_recipient_unread ON public.notifs USING btree (uid, read, created_at DESC) WHERE (archived_at IS NULL);
CREATE INDEX idx_notifs_student_created ON public.notifs USING btree (student_id, created_at DESC) WHERE (student_id IS NOT NULL);
CREATE INDEX idx_notifs_uid_read ON public.notifs USING btree (uid, read);
CREATE UNIQUE INDEX uq_notifs_recipient_dedupe ON public.notifs USING btree (uid, dedupe_key) WHERE (dedupe_key IS NOT NULL);
CREATE INDEX idx_pae_sid_dates ON public.payment_access_exceptions USING btree (sid, starts_at, ends_at) WHERE (revoked_at IS NULL);
CREATE INDEX idx_payment_access_exceptions_granted_by ON public.payment_access_exceptions USING btree (granted_by);
CREATE INDEX idx_payment_access_exceptions_revoked_by ON public.payment_access_exceptions USING btree (revoked_by) WHERE (revoked_by IS NOT NULL);
CREATE INDEX idx_pal_obligation ON public.payment_allocations USING btree (obligation_id);
CREATE INDEX idx_pal_transaction ON public.payment_allocations USING btree (transaction_id);
CREATE INDEX idx_payment_scan_log_checked_by ON public.payment_scan_log USING btree (checked_by);
CREATE INDEX idx_psc_sid_created ON public.payment_scan_log USING btree (sid, created_at DESC);
CREATE INDEX idx_payment_transactions_recorded_by ON public.payment_transactions USING btree (recorded_by);
CREATE INDEX idx_payment_transactions_reversed_by ON public.payment_transactions USING btree (reversed_by) WHERE (reversed_by IS NOT NULL);
CREATE INDEX idx_payment_transactions_sid ON public.payment_transactions USING btree (sid);
CREATE INDEX idx_ptx_sid_year_date ON public.payment_transactions USING btree (sid, school_year, payment_date DESC);
CREATE INDEX idx_payments_sid ON public.payments USING btree (sid);
CREATE INDEX preinscriptions_expiry_idx ON public.preinscriptions USING btree (expire_le) WHERE (statut = 'nouvelle'::text);
CREATE INDEX preinscriptions_identity_idx ON public.preinscriptions USING btree (lower(btrim(nom)), dob);
CREATE INDEX preinscriptions_parent_id_idx ON public.preinscriptions USING btree (parent_id) WHERE (parent_id IS NOT NULL);
CREATE INDEX preinscriptions_phone_idx ON public.preinscriptions USING btree ("right"(regexp_replace(telephone, '[^0-9]+'::text, ''::text, 'g'::text), 8));
CREATE INDEX preinscriptions_status_created_idx ON public.preinscriptions USING btree (statut, created_at DESC);
CREATE INDEX preinscriptions_student_id_idx ON public.preinscriptions USING btree (student_id) WHERE (student_id IS NOT NULL);
CREATE INDEX preinscriptions_traite_par_idx ON public.preinscriptions USING btree (traite_par) WHERE (traite_par IS NOT NULL);
CREATE INDEX idx_prevision_matiere_cid ON public.prevision_matiere USING btree (cid);
CREATE UNIQUE INDEX profiles_email_lower_key ON public.profiles USING btree (lower(email));
CREATE INDEX idx_push_subscriptions_uid ON public.push_subscriptions USING btree (uid);
CREATE INDEX idx_push_subscriptions_user_active ON public.push_subscriptions USING btree (uid, active, last_seen_at DESC);
CREATE UNIQUE INDEX uq_push_subscriptions_provider_token ON public.push_subscriptions USING btree (provider, token) WHERE (token IS NOT NULL);
CREATE INDEX idx_rattrapages_sid ON public.rattrapages USING btree (sid);
CREATE INDEX salaries_user_id_idx ON public.salaries USING btree (user_id);
CREATE INDEX idx_sanctions_sid ON public.sanctions USING btree (sid);
CREATE INDEX idx_scan_log_sid_date ON public.scan_log USING btree (sid, date);
CREATE UNIQUE INDEX scan_log_one_authorized_exit_per_day ON public.scan_log USING btree (sid, date) WHERE ((type = 'exit'::text) AND (status = 'authorized'::text));
CREATE UNIQUE INDEX uq_scan_log_exit_event ON public.scan_log USING btree (exit_event_id) WHERE (exit_event_id IS NOT NULL);
CREATE INDEX idx_school_files_owner ON public.school_files USING btree (owner_type, owner_id, created_at DESC);
CREATE INDEX idx_school_files_year ON public.school_files USING btree (academic_year, archived_at);
CREATE INDEX school_files_idx_administrative_document ON public.school_files USING btree (administrative_document_id, created_at DESC) WHERE ((administrative_document_id IS NOT NULL) AND (deleted_at IS NULL));
CREATE INDEX school_files_idx_archive_lookup ON public.school_files USING btree (academic_year, archived_at DESC) WHERE ((archived_at IS NOT NULL) AND (deleted_at IS NULL));
CREATE INDEX school_files_idx_archived_by ON public.school_files USING btree (archived_by) WHERE (archived_by IS NOT NULL);
CREATE INDEX school_files_idx_cahier_prep ON public.school_files USING btree (cahier_prep_id, created_at DESC) WHERE ((cahier_prep_id IS NOT NULL) AND (deleted_at IS NULL));
CREATE INDEX school_files_idx_deleted_by ON public.school_files USING btree (deleted_by) WHERE (deleted_by IS NOT NULL);
CREATE INDEX school_files_idx_optimization_year ON public.school_files USING btree (academic_year, optimized) WHERE (deleted_at IS NULL);
CREATE INDEX school_files_idx_payment_transaction ON public.school_files USING btree (payment_transaction_id) WHERE ((payment_transaction_id IS NOT NULL) AND (deleted_at IS NULL));
CREATE INDEX school_files_idx_restored_by ON public.school_files USING btree (restored_by) WHERE (restored_by IS NOT NULL);
CREATE UNIQUE INDEX school_files_uq_active_receipt_per_transaction ON public.school_files USING btree (payment_transaction_id) WHERE ((category = 'receipt'::text) AND (payment_transaction_id IS NOT NULL) AND (archived_at IS NULL) AND (deleted_at IS NULL));
CREATE UNIQUE INDEX school_files_uq_uploader_idempotency ON public.school_files USING btree (uploaded_by, idempotency_key) WHERE ((idempotency_key IS NOT NULL) AND (deleted_at IS NULL));
CREATE INDEX idx_student_exit_active_expiry ON public.student_exit_events USING btree (expires_at) WHERE (status = ANY (ARRAY['prepared'::text, 'gate_scanned'::text]));
CREATE INDEX idx_student_exit_history ON public.student_exit_events USING btree (sid, school_date DESC, created_at DESC);
CREATE UNIQUE INDEX uq_student_exit_active_day ON public.student_exit_events USING btree (sid, school_date) WHERE (status = ANY (ARRAY['prepared'::text, 'gate_scanned'::text]));
CREATE UNIQUE INDEX uq_student_exit_confirmed_day ON public.student_exit_events USING btree (sid, school_date) WHERE (status = 'confirmed'::text);
CREATE INDEX idx_sfo_due_active ON public.student_fee_obligations USING btree (due_date, active) WHERE active;
CREATE INDEX idx_sfo_sid_year ON public.student_fee_obligations USING btree (sid, school_year);
CREATE INDEX idx_student_fee_obligations_created_by ON public.student_fee_obligations USING btree (created_by) WHERE (created_by IS NOT NULL);
CREATE INDEX idx_student_fee_obligations_fee_type_id ON public.student_fee_obligations USING btree (fee_type_id);
CREATE INDEX idx_student_fee_obligations_sid ON public.student_fee_obligations USING btree (sid);
CREATE INDEX idx_primary_parent_history_student ON public.student_primary_parent_history USING btree (sid, changed_at DESC);
CREATE INDEX idx_students_cid ON public.students USING btree (cid);
CREATE INDEX idx_students_pid ON public.students USING btree (pid);
CREATE UNIQUE INDEX students_unique_matricule ON public.students USING btree (lower(mat)) WHERE ((mat IS NOT NULL) AND (btrim(mat) <> ''::text));
CREATE UNIQUE INDEX users_phone_e164_unique ON public.users USING btree (phone) WHERE (phone IS NOT NULL);
CREATE INDEX idx_versements_sid_date ON public.versements USING btree (sid, date);

COMMIT;
